CREATE DATABASE LOAN;
USE LOAN;

CREATE TABLE CUSTOMER(CUSTOMER_ID INT PRIMARY KEY ,NAME VARCHAR(20) NOT NULL,
EMAIL VARCHAR(20),PHONE_NUMBER BIGINT,ADDRESS VARCHAR(20),CREDIT_SCORE INT);

DROP TABLE CUSTOMER;
SELECT * FROM CUSTOMER;
INSERT INTO CUSTOMER VALUES(1,"Jeeva","jeeva@gmail.com",98477648,"Chennai",5);
INSERT INTO CUSTOMER VALUES(2,"Megha","megha@gmail.com",87684773,"Bangalore",7);

CREATE TABLE  LOAN(LOAN_ID INT PRIMARY KEY,CUSTOMER_ID INT,PRINCIPAL_AMOUNT DECIMAL(10,2),INTEREST_RATE DECIMAL(5,2),
LOAN_TERM INT,LOAN_TYPE VARCHAR(20),LOAN_STATUS VARCHAR(20),FOREIGN KEY(CUSTOMER_ID) 
REFERENCES CUSTOMER(CUSTOMER_ID) ON UPDATE CASCADE ON DELETE CASCADE);

INSERT INTO LOAN VALUES(101,1,300000,0.5,8,"car loan","pending");

SELECT * FROM LOAN;
DROP TABLE LOAN;

CREATE TABLE HOME_LOAN(PROPERTY_ADDRESS VARCHAR(20),PROPERTY_VALUE INT);
CREATE TABLE CAR_LOAN(CAR_MODEL VARCHAR(20),CAR_VALUE INT);